import {useEffect,useMemo,useRef,useState} from 'react';
import {HouseLine,ListChecks,Plant,Broom,CarProfile,Barbell,BookOpen,Buildings,Plus,Minus,X,CaretRight,Check,ArrowCounterClockwise,Compass,FloppyDisk,CheckCircle,AirplaneTakeoff,TrainSimple,Pause,Play} from '@phosphor-icons/react';
import {CityScene} from './CityScene.jsx';
import {DaylightControl,useCityDaylight} from './DaylightControl.jsx';
import {FinancePanel} from './finance/FinancePanel.tsx';
import {useAccessGate} from './auth/useAccessGate';
import {AccountControl} from './auth/AccountControl';
import {AccessDialog} from './auth/AccessDialog';
import {AccountFlow} from './auth/AccountFlow';
import {HouseholdDialog} from './auth/HouseholdDialog';
import {TravelPanel} from './TravelPanel.jsx';
import {TRAVEL_KEY,initialTravel,isTravelState,reduceTravel} from './travel-state.mjs';
import {districts,tasks,initialState,isValidState,reduceState,derived,taskDone,levelDescriptions,STORAGE_KEY,localDay,demoStateOnly} from './city-state.mjs';
const icons={finance:Buildings,habits:Plant,home:HouseLine,health:Barbell,learning:BookOpen,cars:CarProfile,chores:Broom,airport:AirplaneTakeoff,rail:TrainSimple};
function load(){try{const raw=localStorage.getItem(STORAGE_KEY);const s=raw?JSON.parse(raw):null;return isValidState(s)?demoStateOnly(s):initialState();}catch{return initialState();}}
function loadTravel(){try{const raw=localStorage.getItem(TRAVEL_KEY);if(raw){const parsed=JSON.parse(raw);if(isTravelState(parsed))return parsed;return {version:1,trips:[]};}const seed=initialTravel();localStorage.setItem(TRAVEL_KEY,JSON.stringify(seed));return seed;}catch{return {version:1,trips:[]};}}
export function App(){
 const daylight=useCityDaylight();
 const access=useAccessGate();
 const financeExit=useRef(null);
 const [householdOpen,setHouseholdOpen]=useState(false);
 const [financeVisit,setFinanceVisit]=useState(0);
 const [state,setState]=useState(load),[selected,setSelected]=useState(null),[mode,setMode]=useState('overview'),[activeTask,setActiveTask]=useState('read'),[car,setCar]=useState('car_a');
 const [ready,setReady]=useState(false),[error,setError]=useState(''),[toast,setToast]=useState(null),[previews,setPreviews]=useState({}),[showGrowth,setShowGrowth]=useState(false);
 const [transport,setTransport]=useState({}),[watchDeparture,setWatchDeparture]=useState(false);
 const [travel,setTravel]=useState(loadTravel),[now,setNow]=useState(Date.now),[travelLayout,setTravelLayout]=useState(0),[motionPaused,setMotionPaused]=useState(()=>matchMedia('(prefers-reduced-motion: reduce)').matches);
 const travelLive=useRef(travel);travelLive.current=travel;
 const api=useRef(null),toastTimer=useRef(null),live=useRef(state);live.current=state;
 const realDay=localDay();
 const info=useMemo(()=>derived(state,realDay),[state,realDay]),district=districts.find(d=>d.id===selected),Icon=icons[selected]||HouseLine;
 const date=new Intl.DateTimeFormat('zh-CN',{month:'long',day:'numeric',weekday:'long',timeZone:'Asia/Shanghai'}).format(new Date());
 function commit(action,message){const next=reduceState(live.current,action);if(next===live.current)return;
  try{localStorage.setItem(STORAGE_KEY,JSON.stringify(next));setState(next);live.current=next;setError('');if(message){clearTimeout(toastTimer.current);setToast({message,eventId:action.type==='complete'?next.events.at(-1)?.id:null});toastTimer.current=setTimeout(()=>setToast(null),8000);}}catch{setError('暂时无法保存，请检查浏览器存储后重试。城市状态尚未改变。');}}
 function commitTravel(action){const next=reduceTravel(travelLive.current,action);if(next===travelLive.current)return false;try{localStorage.setItem(TRAVEL_KEY,JSON.stringify(next));travelLive.current=next;setTravel(next);setError('');return true;}catch{setError('行程暂时无法保存在本机，请检查浏览器存储后重试。');return false;}}
 useEffect(()=>{const tick=()=>setNow(Date.now()),timer=setInterval(tick,1000);window.addEventListener('focus',tick);document.addEventListener('visibilitychange',tick);return()=>{clearInterval(timer);window.removeEventListener('focus',tick);document.removeEventListener('visibilitychange',tick);};},[]);
 function complete(t){commit({type:'complete',task:t.id},t.district==='habits'?'花圃又成长了一点':t.district==='cars'?'照顾好了，工位也清爽了':t.district==='chores'?'完成一件，家又轻松了一点':'今天的积累，已留在小城里');}
 function completionEvent(t){return state.events.find(e=>e.task===t.id&&e.day===localDay());}
 function undoTask(t){const e=completionEvent(t);if(e){commit({type:'undo',id:e.id});setToast(null);}}
 function showRegion(id,source='region'){setWatchDeparture(false);setSelected(id);setMode(source);setShowGrowth(false);setPreviews({});if(id==='finance')setFinanceVisit(value=>value+1);if(id==='cars'){const t=info.pending.find(t=>t.district==='cars');if(t)setCar(t.car);}}
 function leave(action){if(financeExit.current)financeExit.current(action);else action();}
 function select(id,source='region'){leave(()=>access.request(id,districts.find(d=>d.id===id)?.name||'这个街区',()=>showRegion(id,source)));}
 function closePanel(){setWatchDeparture(false);setSelected(null);setMode('overview');setPreviews({});setShowGrowth(false);api.current?.reset();}
 function close(){leave(closePanel);}
 function openToday(){if(mode==='today'){close();return;}leave(()=>access.request('today','今日事务',()=>{setMode('today');setSelected(null);setShowGrowth(false);setPreviews({});}));}
 useEffect(()=>{const handler=e=>{if(e.key==='Escape'&&!document.querySelector('dialog[open]'))close();};window.addEventListener('keydown',handler);return()=>{window.removeEventListener('keydown',handler);clearTimeout(toastTimer.current);};},[]);
 useEffect(()=>{if(access.auth.status!=='signedIn'){closePanel();setToast(null);setHouseholdOpen(false);}},[access.auth.status,access.auth.session?.user.id]);
 useEffect(()=>{if(selected==='finance'&&access.auth.status==='signedIn'&&access.profile&&!access.profile.modules.includes('finance')){closePanel();access.denied('财务市区');}},[selected,access.profile]);
 const regionTasks=tasks.filter(t=>t.district===selected&&(!t.car||t.car===car));
 const next=info.pending.find(t=>t.district==='chores')||info.pending[0],actualLevel=info.levels[selected]||1,displayLevel=previews[selected]??actualLevel;
 return <main className="app" data-mode={mode} data-night={daylight.hour<6.1||daylight.hour>=18.65}>
  <CityScene realDay={realDay} state={state} previews={previews} selected={selected} mode={mode} layoutKey={`${showGrowth}:${travelLayout}:${watchDeparture}`} onTransport={setTransport} watchDeparture={watchDeparture} travel={travel} now={now} motionPaused={motionPaused} cityHour={daylight.hour} cityLights={daylight.settings.lights} onSelect={select} onReady={()=>setReady(true)} onError={setError} apiRef={api}/>
  <header className="topbar"><button className="brand" onClick={close} aria-label="回到家庭小城总览"><span className="brand-icon"><HouseLine size={34} weight="duotone"/></span><span><strong>家庭小城</strong><small>{date}</small></span></button><div className="top-actions"><button className={`today-button ${mode==='today'?'active':''}`} onClick={openToday} aria-label="今日事务" aria-expanded={mode==='today'}><ListChecks size={21}/><span>今日事务</span><b>{info.completed}<em>/{tasks.length}</em></b></button><AccountControl onHousehold={()=>leave(()=>access.request('household','家庭成员',()=>{closePanel();setHouseholdOpen(true);}))} access={{...access,logout:()=>leave(access.logout)}} onReset={()=>leave(()=>access.request('today','生活区示例',()=>{commit({type:'reset'},'已恢复示例城市');closePanel();}))}/></div></header>
  <DaylightControl {...daylight}/>
  {mode==='overview'&&<div className="city-message"><span>让家更好，</span><span>从每一天的小进步开始。</span></div>}
  {!ready&&!error&&<div className="loading-panel"><HouseLine size={34} weight="duotone"/><strong>小城正在醒来</strong><span>正在载入三维街区…</span></div>}
  {error&&<div className="error-panel" role="alert"><strong>需要稍等一下</strong><p>{error}</p><button onClick={()=>window.location.reload()}>重新载入</button><button onClick={()=>setError('')} aria-label="关闭提示"><X size={18}/></button></div>}
  {mode==='today'&&access.canOpen('today')&&<aside className="today-drawer" aria-label="今日事务清单"><div className="drawer-heading"><span className="eyebrow">一起照顾生活</span><button className="icon-button" onClick={close} aria-label="关闭今日清单"><X size={19}/></button></div><h1>今天，让小城<br/>更好一点</h1><div className="progress-summary"><span>已完成 {info.completed} / {tasks.length}</span><span>{Math.round(info.completed/tasks.length*100)}%</span></div><div className="progress-track"><i style={{width:`${info.completed/tasks.length*100}%`}}/></div><div className="task-section-label">接下来 <span>{info.pending.length} 件小事</span></div><div className="drawer-tasks">{info.pending.map(t=>{const TI=icons[t.district],active=activeTask===t.id&&selected===t.district;return <div key={t.id} className={`drawer-task ${active?'chosen':''}`}><button className="task-open" onClick={()=>access.request(t.district,districts.find(d=>d.id===t.district)?.name||'今日事务',()=>{setActiveTask(t.id);setSelected(t.district);if(t.car)setCar(t.car);})}><span className="empty-check"/><span><strong>{t.title}</strong><small>{t.detail}</small></span><TI size={18}/></button>{active&&<button className="primary compact" onClick={()=>complete(t)}><Check size={17}/>{t.district==='habits'?'完成今日打卡':'标记完成'}</button>}</div>;})}{!info.pending.length&&<div className="all-done"><CheckCircle size={36} weight="duotone"/><strong>今天照顾好了</strong><span>留点时间，逛逛自己的小城。</span></div>}<details className="completed-list"><summary>已完成 · {info.completed}</summary>{tasks.filter(t=>taskDone(state,t)).map(t=><p key={t.id}><Check size={14}/>{t.title}{completionEvent(t)&&<button className="text-button" aria-label={`撤销${t.title}`} onClick={()=>undoTask(t)}>撤销</button>}</p>)}</details></div><div className="drawer-footer"><Plant size={24} weight="duotone"/><span>不必一下做好所有事。<br/>每一步，城市都会记得。</span></div></aside>}
  {mode==='region'&&district&&access.canOpen(selected)&&<section className={`region-panel ${district.travelMode?'travel-region':''} ${selected==='finance'?'finance-region':''} ${watchDeparture?'departure-cinema':''}`} aria-label={`${district.name}事务`} style={{'--accent':district.color}}><div className="region-header"><span className="region-icon"><Icon size={28} weight="duotone"/></span><div><h1>{district.name}</h1><p>{district.desc}</p></div><div className="panel-header-actions">{levelDescriptions[selected]&&<button className="text-button" onClick={()=>{setShowGrowth(!showGrowth);setPreviews({});}}><Plant size={16}/>成长图鉴</button>}<button className="icon-button" onClick={close} aria-label="关闭区域面板"><X size={19}/></button></div></div>
   {showGrowth?<div className="growth-panel"><div className="level-buttons">{levelDescriptions[selected].map(([name,desc],i)=><button key={name} className={displayLevel===i+1?'selected':''} aria-pressed={displayLevel===i+1} onClick={()=>setPreviews({[selected]:i+1})}><small>Lv.{i+1}</small><strong>{name}</strong><span>{desc}</span></button>)}</div><div className="growth-footer"><span>设施逐步增加，已建成的都会留下。</span><button className="text-button" onClick={()=>setPreviews({})}>返回当前等级 Lv.{actualLevel}</button></div></div>
   :district.travelMode?<TravelPanel key={district.travelMode} mode={district.travelMode} trips={travel.trips} now={now} station={transport[district.travelMode]} watching={watchDeparture} onWatch={()=>setWatchDeparture(v=>!v)} onPreview={()=>{if(transport[district.travelMode]?.preview){api.current?.stopTransportPreview(district.travelMode);}else if(api.current?.previewTransport(district.travelMode)){setWatchDeparture(true);}}} onCommit={commitTravel} onLayout={()=>setTravelLayout(v=>v+1)}/>
   :selected==='finance'?<FinancePanel key={`${access.auth.session?.user.id}:${financeVisit}`} exitGuard={financeExit} onAccessDenied={()=>access.request('finance','财务市区',()=>showRegion('finance'))}/>
   :selected==='home'?<div className="home-content"><div className="home-completion"><CheckCircle size={30} weight="duotone"/><div><strong>今日完成 {info.completed} / {tasks.length}</strong><span>{info.pending.length?`还有 ${info.pending.length} 件小事，慢慢来。`:'今天的生活，照顾好了。'}</span></div></div><span className="level-badge">Lv.{actualLevel} · {levelDescriptions.home[actualLevel-1][0]}</span><button className="primary" onClick={openToday}>看看今日事务 <CaretRight size={18}/></button></div>
   :<div className="region-task-content">{selected==='cars'&&<div className="car-tabs">{[['car_a','蓝色小车'],['car_b','珊瑚小车']].map(([id,name])=>{const n=info.pending.filter(t=>t.car===id).length;return <button key={id} className={car===id?'selected':''} aria-pressed={car===id} onClick={()=>setCar(id)}><CarProfile weight="duotone" size={23}/>{name}<small>{n?`${n} 项待办`:'已照顾好'}</small></button>;})}</div>}{regionTasks.length?regionTasks.map(t=><div className={`region-task-row ${taskDone(state,t)?'done':''}`} key={t.id}><span className={taskDone(state,t)?'checked-circle':'empty-check'}>{taskDone(state,t)&&<Check size={15}/>}</span><div><strong>{t.title}</strong><small>{t.detail}</small></div>{taskDone(state,t)?<span className="done-text">今日已完成{completionEvent(t)&&<button className="text-button" aria-label={`撤销${t.title}`} onClick={()=>undoTask(t)}>撤销</button>}</span>:<button className="primary" onClick={()=>complete(t)}>{selected==='habits'?'完成打卡':'标记完成'}<Check size={17}/></button>}</div>):<p>今天暂时没有安排，逛逛这个街区吧。</p>}</div>}
  </section>}
  {mode==='overview'&&ready&&<div className="next-card"><span className="next-icon"><Broom size={31} weight="duotone"/></span><div><strong>{next?'再做一件，小城更好':'今天照顾好了'}</strong><span>{next?`${next.title} · ${districts.find(d=>d.id===next.district).short}`:'留点时间，享受自己的小城'}</span></div><button className="primary" onClick={()=>next?select(next.district):openToday()}>{next?'去看看':'今日记录'}<CaretRight size={17}/></button></div>}
  <nav className="district-directory" aria-label="区域目录">{districts.map(d=>{const I=icons[d.id];return <button key={d.id} className={selected===d.id?'active':''} aria-label={`前往${d.name}`} title={d.name} onClick={()=>select(d.id)}><I size={20} weight={selected===d.id?'fill':'regular'}/><span>{d.short}</span></button>;})}</nav>
  <div className="map-controls"><button className="compass-button" onClick={()=>api.current?.rotate()} aria-label="旋转视角90度"><span>N</span><Compass size={31} weight="duotone"/></button><div className="zoom-buttons"><button onClick={()=>api.current?.zoom(.2)} aria-label="放大地图"><Plus size={22}/></button><button onClick={()=>api.current?.zoom(-.2)} aria-label="缩小地图"><Minus size={22}/></button></div><button className="reset-view" onClick={close}><HouseLine size={17} weight="fill"/>回到全城</button><button className="motion-toggle" aria-pressed={motionPaused} aria-label={motionPaused?'播放城市人流车流':'暂停城市人流车流'} onClick={()=>setMotionPaused(v=>!v)}>{motionPaused?<Play size={14}/>:<Pause size={14}/>}<span>{motionPaused?'继续漫游':'暂停漫游'}</span></button><small>拖动旋转 · 滚轮缩放</small></div>
  {toast&&<div className="toast" role="status"><CheckCircle size={23} weight="fill"/><span>{toast.message}</span>{toast.eventId&&<button onClick={()=>{commit({type:'undo',id:toast.eventId});setToast(null);}}><ArrowCounterClockwise size={16}/>撤销</button>}</div>}
  <AccessDialog access={access}/>
  <AccountFlow access={access}/>
  {householdOpen&&access.canOpen('household')&&<HouseholdDialog key={access.auth.session?.user.id} access={access} onClose={()=>setHouseholdOpen(false)}/>}
  <div className="sr-only" aria-live="polite">{selected?`已选择${district?.name}`:'全城总览'}，今日完成{info.completed}项。</div>
 </main>;
}
